baseURL = "https://robert-mcdermott.github.io/"
languageCode = "en-us"
title = "Robert McDermott"
theme = "vienna"
copyright = "Robert McDermott &nbsp; &ltrobert.c.mcdermott@gmail.com&gt"

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    #twitter = "Your Twitter username"
    #github = "robert-mcdermott"
    #linkedin = "Robert-mcdermott-a77b9011"
    #facebook = "Your Facebook username"
    # Disqus shortname
    disqus = "robert-mcdermott-github-io"
    #author = "Robert McDermott"
    #avatar = "/images/me.jpg"
    #contact = "mailto:robert.c.mcdermott@gmail.com"
    #bio = ""
    #Short subtitle/tagline. This is displayed in the header.
    subtitle = "Random Technical Stuff"
    themecolor = "#0000ff" # Defines the tab color in Chrome for Android.

